### ISSUE TITLE
❌ ERROR: MAXIMUM CALL STACK SIZE EXCEEDED

### ISSUE THREAD

**Issue by noobbuilder69** [Offsetra/ethereum-emissions-calculator#8]
Anyway to calculate the total footprint of entire smart contract?
Tried looking up $shib token contract to see how much approximate carbon usage but threw this error

**Comment by noobbuilder69** [comment]
@brendanmc6  :-)

**Comment by brendanmc6** [comment]
Sorry for the silence, I'm looking into this!

**Comment by brendanmc6** [comment]
Ah yes, very large contracts... This is actually the first one I've tried that blows up the call stack. In my previous testing it would just run forever until it finally found the end.

Here is how I think we can solve this - @de-souza  I think this would be a fun one for you if you are up for it...
- [ ] replace the recursive `getTransactions` function with a single query result.
https://github.com/Offsetra/ethereum-emissions-calculator/blob/90b68ad16c1fad67d79b74dd5263e85163e72be7/src/index.ts#L92
- [ ] Query result should calculate the gas/co2 for that chunk of blocks (to allow garbage collection of the array of records)
- [ ] The query result should return the highest block number (this can be used to indicate a loading status too).
- [ ] The query result should return either a `.next()` function or a `status` property.
- [ ] Rather than looping/recursing in this package, the app implementation (carbon.fyi) should handle looping and re-querying until the final set of blocks has been read.

**Comment by brendanmc6** [comment]
Still blowing the stack for very large addresses... working on a fix

**Comment by brendanmc6** [comment]
Fixed in v2.0 https://github.com/Offsetra/ethereum-emissions-calculator/commit/67988057b026e54df7e08453faf14eb744f14e03
